version: "3.8"
services:
  api:
    container_name: "SignalR-Server"
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - ConnectionStrings__DefaultConnection=Server=127.0.0.120,1433;Database=AdvancedNetTraining;User Id=sa;Password=DSAdsa@123;TrustServerCertificate=True
    restart: always
    depends_on:
      - db

  db:
    container_name: "SQLServer"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: DSAdsa@123
    restart: always
    ports:
      - "1433:1433"